export type SelectionStatus = '書類' | 'SPI' | '面接' | 'コーディングテスト' | '合格' | '不合格';
export type SelectionCategory = '지원 준비' | '진행 중인 전형' | '합격' | '불합격';

export interface SelectionItem {
  id: string;
  name_ko: string;
  name_ja: string;
  industry: string;
  region: string;
  logo_url: string;
  description_ko: string;
  description_ja: string;
  position_ko: string;
  position_ja: string;
  tech_stacks: string[];
  status: SelectionStatus;
  current_stage_label?: string;
  match_score: number;
  next_event_label?: string;
  next_event_date?: string;
}

export function getCategory(status: SelectionStatus): SelectionCategory {
  if (status === '合格') return '합격';
  if (status === '不合格') return '불합격';
  if (status === '書類') return '지원 준비';
  return '진행 중인 전형';
}

// seed: backend/db/seed/mock_data.sql 기반, 프론트 개발용 확장 mock
export const MOCK_SELECTIONS: SelectionItem[] = [
  // ── 지원 준비 (書類) ──────────────────────────────────────────
  {
    id: 'uc-mock-p01',
    name_ko: 'LINE',
    name_ja: 'LINE',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/line.png',
    description_ko: '일본 최대 메시지 플랫폼 운영',
    description_ja: '国内最大のメッセージングプラットフォーム運営',
    position_ko: '풀스택 엔지니어',
    position_ja: 'フルスタックエンジニア',
    tech_stacks: ['Go', 'gRPC', 'k8s'],
    status: '書類',
    match_score: 72,
    next_event_label: '서류 마감',
    next_event_date: '2026-05-13',
  },
  {
    id: 'uc-mock-p02',
    name_ko: '조조타운',
    name_ja: 'ZOZO',
    industry: '커머스',
    region: '東京',
    logo_url: '/logos/zozo.png',
    description_ko: '패션 EC 최대 기업, ZOZOTOWN 운영',
    description_ja: 'ファッションECの最大手、ZOZOTOWNを運営',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Go', 'TypeScript', 'BigQuery'],
    status: '書類',
    match_score: 68,
    next_event_label: '서류 마감',
    next_event_date: '2026-05-25',
  },
  {
    id: 'uc-mock-p03',
    name_ko: '드왕고',
    name_ja: 'ドワンゴ',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/dwango.png',
    description_ko: '니코니코 동화 등 동영상 서비스 운영',
    description_ja: 'ニコニコ動画など動画配信サービスを運営',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Scala', 'Go', 'k8s'],
    status: '書類',
    match_score: 62,
    next_event_label: '서류 마감',
    next_event_date: '2026-06-05',
  },
  {
    id: 'uc-mock-p04',
    name_ko: '머니포워드',
    name_ja: 'マネーフォワード',
    industry: '금융',
    region: '東京',
    logo_url: '/logos/moneyforward.png',
    description_ko: '클라우드 회계·가계부 앱 운영 FinTech 기업',
    description_ja: 'クラウド会計・家計簿アプリを運営するFinTech企業',
    position_ko: '프론트엔드 엔지니어',
    position_ja: 'フロントエンドエンジニア',
    tech_stacks: ['Ruby', 'React', 'AWS'],
    status: '書類',
    match_score: 57,
    next_event_label: '서류 마감',
    next_event_date: '2026-06-10',
  },
  // ── 진행 중인 전형 (SPI / 面接 / コーディングテスト) ──────────────
  {
    // seed: uc-0001-0000-0000-000000000001 (メルカリ, 面接)
    id: 'uc-0001-0000-0000-000000000001',
    name_ko: '메루카리',
    name_ja: 'メルカリ',
    industry: 'EC',
    region: '東京',
    logo_url: '/logos/mercari.png',
    description_ko: '프리마 앱 1위, 개인거래 플랫폼 운영',
    description_ja: 'フリマアプリNo.1。個人間取引プラットフォームを展開',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Go', 'MySQL'],
    status: '面接',
    current_stage_label: '1차 면접',
    match_score: 87,
    next_event_label: '1차 면접',
    next_event_date: '2026-05-01',
  },
  {
    id: 'uc-mock-a02',
    name_ko: 'GMO',
    name_ja: 'GMO',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/gmo.png',
    description_ko: '인터넷 인프라에서 FinTech까지 폭넓게 전개',
    description_ja: 'インターネットインフラからFinTechまで幅広く展開',
    position_ko: '프론트엔드 엔지니어',
    position_ja: 'フロントエンドエンジニア',
    tech_stacks: ['React', 'PHP', 'MySQL'],
    status: 'コーディングテスト',
    current_stage_label: '코딩 테스트',
    match_score: 70,
    next_event_label: '코딩 테스트',
    next_event_date: '2026-05-10',
  },
  {
    // seed: uc-0001-0000-0000-000000000004 (LINE データエンジニア, SPI)
    id: 'uc-0001-0000-0000-000000000004',
    name_ko: 'LINE',
    name_ja: 'LINE',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/line.png',
    description_ko: '일본 최대 커뮤니케이션 앱 운영',
    description_ja: 'コミュニケーションアプリLINE',
    position_ko: '데이터 엔지니어',
    position_ja: 'データエンジニア',
    tech_stacks: ['TypeScript', 'PostgreSQL'],
    status: 'SPI',
    current_stage_label: 'SPI',
    match_score: 65,
    next_event_label: 'SPI',
    next_event_date: '2026-05-15',
  },
  {
    id: 'uc-mock-a04',
    name_ko: '리쿠르트',
    name_ja: 'リクルート',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/recruit.png',
    description_ko: '리크나비・じゃらん 등 다양한 서비스 운영',
    description_ja: 'リクナビ・じゃらんなど多様なサービスを展開',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Java', 'React', 'AWS'],
    status: 'SPI',
    current_stage_label: 'SPI',
    match_score: 60,
    next_event_label: 'SPI',
    next_event_date: '2026-05-18',
  },
  {
    // seed: uc-0001-0000-0000-000000000005 (サイバーエージェント backend, 面接)
    id: 'uc-0001-0000-0000-000000000005',
    name_ko: '사이버에이전트',
    name_ja: 'サイバーエージェント',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/cyberagent.png',
    description_ko: '인터넷 종합 기업',
    description_ja: 'インターネットの総合企業',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['React', 'NestJS'],
    status: '面接',
    current_stage_label: '2차 면접',
    match_score: 80,
    next_event_label: '2차 면접',
    next_event_date: '2026-05-20',
  },
  // ── 합격 (合格) ──────────────────────────────────────────────
  {
    // seed: uc-0001-0000-0000-000000000006 (楽天, 合格)
    id: 'uc-0001-0000-0000-000000000006',
    name_ko: '라쿠텐',
    name_ja: '楽天',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/rakuten.png',
    description_ko: '일본 최대 규모 EC/플랫폼 기업',
    description_ja: '日本最大級のEC/プラットフォーム企業',
    position_ko: '클라우드 엔지니어',
    position_ja: 'クラウドエンジニア',
    tech_stacks: ['PostgreSQL', 'Docker'],
    status: '合格',
    match_score: 91,
  },
  {
    id: 'uc-mock-g02',
    name_ko: '믹시',
    name_ja: 'ミクシィ',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/mixi.png',
    description_ko: 'SNS·게임 서비스 운영',
    description_ja: 'SNS・ゲームサービスを運営',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Go', 'MySQL'],
    status: '合格',
    match_score: 76,
  },
  {
    id: 'uc-mock-g03',
    name_ko: '그리',
    name_ja: 'GREE',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/gree.png',
    description_ko: '소셜 게임 플랫폼 운영',
    description_ja: 'ソーシャルゲームプラットフォームを運営',
    position_ko: '프론트엔드 엔지니어',
    position_ja: 'フロントエンドエンジニア',
    tech_stacks: ['React', 'TypeScript'],
    status: '合格',
    match_score: 71,
  },
  // ── 불합격 (不合格) ───────────────────────────────────────────
  {
    // seed: uc-0001-0000-0000-000000000003 (サイバーエージェント frontend, 不合格)
    id: 'uc-0001-0000-0000-000000000003',
    name_ko: '사이버에이전트',
    name_ja: 'サイバーエージェント',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/cyberagent.png',
    description_ko: '인터넷 종합 기업',
    description_ja: 'インターネットの総合企業',
    position_ko: '프론트엔드 엔지니어',
    position_ja: 'フロントエンドエンジニア',
    tech_stacks: ['React', 'TypeScript', 'NestJS'],
    status: '不合格',
    match_score: 78,
  },
  {
    id: 'uc-mock-f02',
    name_ko: 'DeNA',
    name_ja: 'DeNA',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/dena.png',
    description_ko: '모바일 게임·헬스케어 서비스 운영',
    description_ja: 'モバイルゲーム・ヘルスケアサービスを展開',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Go', 'MySQL'],
    status: '不合格',
    match_score: 74,
  },
  {
    id: 'uc-mock-f03',
    name_ko: '코나미',
    name_ja: 'コナミ',
    industry: 'IT',
    region: '東京',
    logo_url: '/logos/konami.png',
    description_ko: '게임·스포츠·헬스케어 서비스 운영',
    description_ja: 'ゲーム・スポーツ・ヘルスケアサービスを展開',
    position_ko: '백엔드 엔지니어',
    position_ja: 'バックエンドエンジニア',
    tech_stacks: ['Java', 'MySQL'],
    status: '不合格',
    match_score: 69,
  },
];
